In [1]:
import pandas as pd

In [30]:
# To read the csv file using pandas
df = pd.read_csv('terrorismData.csv',encoding = 'ISO-8859-1')

In [31]:
# TO check column top 10 values
df.head(10)

,Year,Month,Day,Country,Region,State,City,Latitude,Longitude,AttackType,Killed,Wounded,Target_Type,Group,Target,TotalAttacks
0,1970,7,2,Dominican Republic,Central America & Caribbean,NaN,Santo Domingo,18.456792,-69.951164,Assassination,1.0,0.0,Private Citizens & Property,MANO-D,Julio Guzman,1
1,1970,0,0,Mexico,North America,Federal,Mexico city,19.371887,-99.086624,Hostage Taking (Kidnapping),0.0,0.0,Government (Diplomatic),23rd of September Communist League,"Nadine Chaval, daughter",6
2,1970,1,0,Philippines,Southeast Asia,Tarlac,Unknown,15.478598,120.599741,Assassination,1.0,0.0,Journalists & Media,Unknown,Employee,1
3,1970,1,0,Greece,Western Europe,Attica,Athens,37.997490,23.762728,Bombing/Explosion,NaN,NaN,Government (Diplomatic),Unknown,U.S. Embassy,3
4,1970,1,0,Japan,East Asia,Fukouka,Fukouka,33.580412,130.396361,Facility/Infrastructure Attack,NaN,NaN,Government (Diplomatic),Unknown,U.S. Consulate,7
5,1970,1,1,United States,North America,Illinois,Cairo,37.005105,-89.176269,Armed Assault,0.0,0.0,Police,Black Nationalists,Cairo Police Headquarters,2
6,1970,1,2,Uruguay,South America,Montevideo,Montevideo,-34.891151,-56.187214,Assassination,0.0,0.0,Police,Tupamaros (Uruguay),Juan Maria de Lucah/Chief of Directorate of in...,1
7,1970,1,2,United States,North America,California,Oakland,37.791927,-122.225906,Bombing/Explosion,0.0,0.0,Utilities,Unknown,Edes Substation,3
8,1970,1,2,United States,North America,Wisconsin,Madison,43.076592,-89.412488,Facility/Infrastructure Attack,0.0,0.0,Military,New Year's Gang,"R.O.T.C. offices at University of Wisconsin, M...",7
9,1970,1,3,United States,North America,Wisconsin,Madison,43.072950,-89.386694,Facility/Infrastructure Attack,0.0,0.0,Government (General),New Year's Gang,Selective Service Headquarters in Madison Wisc...,7

In [38]:
# To check the column bottom 10 values
df.tail(10)

,Year,Month,Day,Country,Region,State,City,Latitude,Longitude,AttackType,Killed,Wounded,Target_Type,Group,Target,TotalAttacks
181681,2017,12,31,Philippines,Southeast Asia,Maguindanao,Shariff Aguak,6.862806,124.443649,Bombing/Explosion,1.0,5.0,Police,Bangsamoro Islamic Freedom Movement (BIFM),Patrol,3
181682,2017,12,31,Italy,Western Europe,Marche,Spinetoli,42.888982,13.772795,Facility/Infrastructure Attack,0.0,0.0,Private Citizens & Property,Unknown,Migrant Center,7
181683,2017,12,31,Afghanistan,South Asia,Faryab,Kohistan district,35.315467,64.815508,Armed Assault,6.0,0.0,Terrorists/Non-State Militia,Taliban,House of Member,2
181684,2017,12,31,India,South Asia,Assam,Hungrum,25.180162,93.015788,Hostage Taking (Kidnapping),0.0,0.0,Government (General),Zeliangrong United Front,Personal Security Officer of Council Member Ih...,6
181685,2017,12,31,Afghanistan,South Asia,Faryab,Maymana,35.921051,64.774544,Bombing/Explosion,0.0,4.0,Business,Unknown,Jewelry Shop,3
181686,2017,12,31,Somalia,Sub-Saharan Africa,Middle Shebelle,Ceelka Geelow,2.359673,45.385034,Armed Assault,1.0,2.0,Military,Al-Shabaab,Checkpoint,2
181687,2017,12,31,Syria,Middle East & North Africa,Lattakia,Jableh,35.407278,35.942679,Bombing/Explosion,2.0,7.0,Military,Muslim extremists,Hmeymim Air Base,3
181688,2017,12,31,Philippines,Southeast Asia,Maguindanao,Kubentog,6.900742,124.437908,Facility/Infrastructure Attack,0.0,0.0,Private Citizens & Property,Bangsamoro Islamic Freedom Movement (BIFM),Houses,7
181689,2017,12,31,India,South Asia,Manipur,Imphal,24.798346,93.940430,Bombing/Explosion,0.0,0.0,Government (General),Unknown,Office,3
181690,2017,12,31,Philippines,Southeast Asia,Maguindanao,Cotabato City,7.209594,124.241966,Bombing/Explosion,0.0,0.0,Unknown,Unknown,Unknown,3

In [39]:
# TO check the column names
col_Names = list(df)
print(col_Names)

['Year', 'Month', 'Day', 'Country', 'Region', 'State', 'City', 'Latitude', 'Longitude', 'AttackType', 'Killed', 'Wounded', 'Target_Type', 'Group', 'Target', 'TotalAttacks']

##### Find the most dangerous city in Jammu and Kashmir and the terrorist group which is most active in that city?
##### Print count of number of attacks in that city as integer value.

##### Print City, Number of Attack, and Group Most Active

In [40]:
# First find the data with only city as Jammu and Kashmir
# Take J nad K state values
new_df = df[df['State'] == 'Jammu and Kashmir']
# new_df.head(10)

# count the frequency of city in the state
city_list = new_df['City'].value_counts()
print(city_list)

City
Srinagar     657
Sopore       102
Unknown       86
Anantnag      76
Jammu         57
            ...
Bragam         1
Narsu          1
Lasjan         1
Goriwan        1
Lethapora      1
Name: count, Length: 633, dtype: int64

In [41]:
# We can see the most city involved means the most terror attacks
ans1 = city_list.index[0]
ans2 = city_list.values[0]
print(ans1,ans2)

Srinagar 657

In [42]:
# Get all the values of the city with srinagar
g_df = new_df[new_df['City'] != ans1]
Group = g_df['Group'].value_counts() # Count the give the sum of different values in the column
# print(Group)
ans3 = Group.index[1]
print(ans1,ans2,ans3)

Srinagar 657 Hizbul Mujahideen (HM)

##### Take the data after the 26th of May 2014
##### Count total number of attacks done in India
##### Which terrorist group was most active
##### Ignore the Unknown Group

In [ ]:
nd = df[df['Country'] == 'India']
print(nd)

In [55]:
new_df = df[df['Country'] == 'India']
new_df = new_df[new_df['Day'] >= 26]
new_df = new_df[new_df['Month'] > 5]
new_df = new_df[new_df['Year'] > 2013]
new_df = new_df.where(new_df['Group'] != 'Unknown')
new_df.head()

,Year,Month,Day,Country,Region,State,City,Latitude,Longitude,AttackType,Killed,Wounded,Target_Type,Group,Target,TotalAttacks
133974,2014.0,6.0,26.0,India,South Asia,Maharashtra,Gadchiroli district,20.184871,79.994796,Armed Assault,2.0,0.0,Police,Maoists,District Patrol,2.0
134043,2014.0,6.0,28.0,India,South Asia,Jharkhand,Latehar district,23.750000,84.500000,Armed Assault,0.0,4.0,Private Citizens & Property,Maoists,Jeep,2.0
134068,2014.0,6.0,29.0,India,South Asia,Meghalaya,Gasuapara,25.224080,90.376665,Hostage Taking (Kidnapping),0.0,0.0,Private Citizens & Property,Achik National Volunteer Council-B (ANVC-B),Shoe Trader: Tapan Saha,6.0
134071,2014.0,6.0,29.0,India,South Asia,Meghalaya,Rongge,25.945488,90.600981,Hostage Taking (Kidnapping),0.0,0.0,Private Citizens & Property,Achik Songna An'pachakgipa Kotok (ASAK),Welder: Manoranjan,6.0
134130,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [63]:
ans1 = new_df['TotalAttacks'].sum()
Group = new_df['Group'].value_counts()
ans2 = Group.index[0]
print('Total number of attacks in India : {0} and Most active Group in India at that time was {1}'.format(ans1,ans2))

Total number of attacks in India : 916.0 and Most active Group in India at that time was Maoists

##### Find Frequency of the casualty in Red Corridor States and in Jammu and Kashmir? 
##### Frequency = Total Casualty/ Total number of year
##### Note : Red Corridor state includes Jharkhand, Odisha, Andhra Pradesh, and Chhattisgarh
##### Casualty = Killed + Wounded
##### Answer = Freq1 , Freq2

In [113]:
import numpy as np

# Creating new col = col[Killed] + col[wounded]
df['Casualty'] = df['Killed'] + df['Wounded']

# Replace NaN value with 0
df.fillna(0,inplace=True)
print(df.head(10))

# Create the set of the column name and count the length for total Number of years
T_year = len(set(df["Year"]))

new_df = df[df['Country'] == 'India']
# new_df['Casualty'] = new_df['Killed'] + new_df['Wounded']
# print(new_df['City'].value_counts())

# Creating Red Corridor states data
Red_C = new_df[(df.State == 'Jharkhand') | (df.State == 'Odisha') | (df.State == 'Andhra Pradesh') | (df.State == 'Chhattisgarh')]

# print(new_df.head())
# Creating J & K data
JK = new_df[df.State == 'Jammu and Kashmir']

sumJk = int(np.sum(JK['Casualty']))
sumRed_C = int(np.sum(Red_C['Casualty']))

Freq1 = sumRed_C//T_year
Freq2 = sumJk//T_year
print(Freq1,Freq2)

      Year  Month  Day Country      Region        State        City  \
1186  1972      2   22   India  South Asia        Delhi   New Delhi
2764  1975      1    2   India  South Asia        Bihar  Samastipur
3857  1976      5   26   India  South Asia        Delhi   New Delhi
5327  1977      9   28   India  South Asia  Maharashtra      Bombay
7337  1979      1   13   India  South Asia        Assam     Unknown
7342  1979      1   14   India  South Asia      Manipur      Imphal
8174  1979      4   26   India  South Asia      Manipur     Unknown
8685  1979      6   14   India  South Asia      Mizoram     Unknown
8831  1979      7    1   India  South Asia        Assam     Unknown
8836  1979      7    2   India  South Asia      Mizoram      Aizawl

       Latitude  Longitude                      AttackType  Killed  Wounded  \
1186  28.585836  77.153336                       Hijacking     0.0      0.0
2764  25.863042  85.781004               Bombing/Explosion     4.0      0.0
3857  28.585836  77.153336               Bombing/Explosion     0.0      0.0
5327  19.075984  72.877656                       Hijacking     0.0      0.0
7337  26.200605  92.937574                   Armed Assault     0.0      0.0
7342  24.798346  93.940430                   Assassination     3.0      0.0
8174  24.663717  93.906269                   Armed Assault     4.0      0.0
8685  23.164543  92.937574                   Assassination     1.0      0.0
8831  26.200604  92.937574                   Armed Assault     2.0      2.0
8836  23.727107  92.717639  Facility/Infrastructure Attack     0.0      0.0

               Target_Type                    Group  \
1186   Airports & Aircraft             Palestinians
2764  Government (General)             Ananda Marga
3857   Airports & Aircraft                  Unknown
5327   Airports & Aircraft  Japanese Red Army (JRA)
7337                Police              Naga People
7342  Government (General)                  Unknown
8174                Police        Meitei extremists
8685  Government (General)      Mizo National Front
8831  Government (General)      Mizo National Front
8836                Police      Mizo National Front

                                                 Target  TotalAttacks  \
1186                                              B-747             4
2764              Lalit Narayan Mishra and a legislator             3
3857                                  New Delhi airport             3
5327                                               DC-8             4
7337                                             patrol             2
7342  Sudhir Kumar Singh, R.K. Sanajoaba Singh, Indr...             1
8174             Indian security force in front of jeep             2
8685                                Government Official             1
8831                                  Magistrates house             2
8836                                            complex             7

      Casualty
1186       0.0
2764       4.0
3857       0.0
5327       0.0
7337       0.0
7342       3.0
8174       4.0
8685       1.0
8831       4.0
8836       0.0
134 301

#### PROBLEM STATEMENT
##### Most Deadliest attack 
##### Print Number of people killed, Country, Group

In [108]:
# Find the Max value from the Killed Column
Max_Killed = max(df['Killed'])


# With the help of max_killed value find the Group who did it.
# df['Where killed = MaxValue'][Group]
group = df[df['Killed'] == Max_Killed]['Group'].values[0]

# With the same logic find the Country where the most number of people killed
Country = df[df['Killed'] == Max_Killed]['Country'].values[0]


print(int(Max_Killed),Country,group)

188 India Lashkar-e-Taiba (LeT)

#### PROBLEM STATEMENT
##### Country with the highest number of Terror attacks and in which year the most number of attacks were done
##### Print Country, NumberOfAttack, Year

In [128]:
ndf = pd.read_csv('terrorismData.csv',encoding='ISO-8859-1')
# print(ndf.head(10))

# Count the most named country in the dataset
N_c = ndf['Country'].value_counts()

# Take the top most country with highest count.
ans1 = N_c.index[0]

# With the country name get all the attacks done on the same country by np.sum() function
new_df1 = ndf[ndf['Country'] == ans1]
ans2 = np.sum(new_df1['TotalAttacks'])

# To calculate most attacks done use the same data set and count the years col which gives the answer
yr = new_df1['Year'].value_counts()
# Take the top most index value form the dataset
ans3 = yr.index[0]
print(ans1,ans2,ans3)


# To calculate the attacks in the year 2014
n_df = new_df1[new_df1['Year'] == 2014]
T_yr = np.sum(n_df['TotalAttacks'])
print("Total Attacks in the year 2017 : {}".format(T_yr))

Iraq 76314 2014
Total Attacks in the year 2017 : 12313